### ISSUE TITLE
FMF EMR 0.9.7 non admin users shouldn't be allowed to update forms

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#128]
Any user of FMF can trigger an update of xml forms by adding forms in ~/freemedforms/Documents/forms
It is a major security risk: any user could potentially erase existing forms and thus shut down the EMR until an admin restores fmf_xmlforms database. Worse: any user could inject malicious js scripts that could damage or destroy medical data in other databases and shutdown the EMR.

We should limit forms upgrade to admin users.
FMF could warn users of an existing upgrade and ask them to log in as admin so that it can be performed, or ask their sysadmin / support team to perform it.

**Comment by jeromecc** [comment]
So we should warn normal users about the update with a QMessageBox and probably add a checkbox to allow each user to disable the warning with void QMessageBox::setCheckBox(QCheckBox *cb) available since Qt 5.2
We need to add a DataRepresentation in UserModel to store the answer: what about FormUpdateNotification which could be true by default (warn the user about form update) or set to false by user (do not warn user about update)?

**Comment by jeromecc** [comment]
So we should warn normal users about the update with a QMessageBox and probably add a checkbox to allow each user to disable the warning with void QMessageBox::setCheckBox(QCheckBox *cb) available since Qt 5.2
We need to add a DataRepresentation in UserModel to store the answer: what about FormUpdateNotification which could be true by default (warn the user about form update) or set to false by user (do not warn user about update)?

**Comment by EricMaeker** [comment]
Not to be implemented
