### ISSUE TITLE
FMF EMR 0.9.8 Documents header, footer, watermak not updated until restart

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#141]
1. Change content of user documents header, footer or watermak
2. save changes
3. print a document
4. changes do not appear
5. close FMF
6. restart FMF
7. print a document
8. changes appear

Estimated time to solve this issue: 2 hours
Estimated sponsorship amount: 50€ (55$)
You can sponsor this bug on https://freedomsponsors.org/issue/779/fmf-emr-098-documents-header-footer-watermak-not-updated-until-restart?alert=KICKSTART

**Comment by EricMaeker** [comment]
Done V1.0.0
