### ISSUE TITLE
FMF EMR 0.9.8 segfault if ui file absent

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#158]
1. create form with absent file on ui file path set in central.xml
2. try adding this new form in the form tree
3. segfault
   
   "XmlReader                 *\* ERROR(xmlformcontentreader.cpp:763) *\* Content not in base???\n                          **subForms**/generic/clinical_letter; mode:central;filename:.\n                          /scripts/xx/medical_letter.js"
   ASSERT: "false" in file xmlformcontentreader.cpp, line 764
   The program has unexpectedly finished.

FMF should not segfault but warn about the problem.

**Comment by jeromecc** [comment]
Same problem with .js files

**Comment by EricMaeker** [comment]
Ok that was a Q_ASSERT() which causes an app segfault in debug compilation. In release mode compilation the Q_ASSERT is non operative.
Removed in v1.0.0
