### ISSUE TITLE
Enhancement: default country for newly created patients

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#20]
In Options / Patient database / Patients / New patient

FMF allow us to choose:
Default city
Default zipcode

Could it allow us to choose
Default country?

Thanks.

**Comment by jeromecc** [comment]
in file patientcreatorwizzard.cpp:
m_Model->setData(m_Model->index(0, Core::IPatient::Country), Utils::countryToIso(QLocale().country()));
FMF selects default country according to system language settings. The problem is that not all combinations of language_COUNTRY exist in Debian. For instance, fr_MG doesn't exist, so doctors in Madagascar (who use French as their medical language) can't use this feature.
We should give our users the possibility to override this automatic selection based on system locales.

**Comment by EricMaeker** [comment]
Done V1.0.0
