### ISSUE TITLE
INN prescription by default in preferences

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#31]
INN prescription became mandatory in France since 01/01/2015.

FMF has enabled its users to prescribe with INN since day 1, but they have to check "Used for INN prescription" for each drug.

Could we add "Use INN by default" in  Preferences/Drugs?

Thanks.

**Comment by jeromecc** [comment]
I tried to hack the code (plugins/drugsplugin/dosagedialog/dosageviewer.cpp .h .ui) but it didn't work out well... :-) We could setChecked by default (if INN linking is possible dosageCanLinkWithInn() ).

**Comment by EricMaeker** [comment]
Done v1.0.0
