### ISSUE TITLE
FMF EMR 0.9.6 Not possible to use "&" character inside <label> </label> tags

### ISSUE THREAD

**Issue by jeromecc** [EricMaeker/freemedforms#79]
Using "&" char (ampersand) inside label tags for group triggers this error:

File /media/data/git/buildfmf/qt5freemedforms/global_resources/forms/subforms/imaging/ultrasound/trimester2/central.xml is not readable

Error letter is expected: line 1082, column 39

**Comment by EricMaeker** [comment]
Use &amp; instead of &
Send your xml file for a better analyse
